package jcucumberng.framework.enums;

public enum ByMethod {
	ID, NAME, LINK_TEXT, PARTIAL_LINK_TEXT, TAG, CLASS, CSS, XPATH, BINDING, MODEL, BUTTON_TEXT, CSS_CONTAINING_TEXT,
	EXACT_BINDING, EXACT_REPEATER, OPTIONS, PARTIAL_BUTTON_TEXT, REPEATER
}
