@echo OFF
set TOOL_HOME=c:\java
if "%GRADLE_VERSION%"=="" set GRADLE_VERSION=3.0
set GRADLE_HOME=%TOOL_HOME%\gradle-%GRADLE_VERSION%
if "%GROOVY_VERSION%"==""  set GROOVY_VERSION=2.4.4
set GROOVY_HOME=%TOOL_HOME%\groovy-%GROOVY_VERSION%

if "%JAVA_VERSION%"=="" set JAVA_VERSION=1.8.0_101
set JAVA_HOME=%TOOL_HOME%\jdk%JAVA_VERSION%
set JAVA_OPTS=-Xms256m -Xmx512m
PATH=%JAVA_HOME%\bin;%PATH%;%GROOVY_HOME%\bin

katalon.exe